export const AI_TRACKS = [
  {
    id: "fundamentals",
    title: "프롬프트와 맥락 설계",
    description: "AI에게 필요한 정보와 답변 기준을 명확하게 전달하세요.",
    outcome: "프롬프트, 토큰, 컨텍스트 이해",
    icon: "sparkles",
  },
  {
    id: "agents",
    title: "AI 에이전트 워크플로우",
    description: "AI에게 맡길 일과 사람이 확인할 일을 나누세요.",
    outcome: "작업 순서와 도구 사용 범위 정하기",
    icon: "workflow",
  },
  {
    id: "frameworks",
    title: "LangChain과 LangGraph",
    description: "모델과 도구를 연결하고 작업의 분기와 재개를 설계하세요.",
    outcome: "에이전트 구성과 상태 관리",
    icon: "workflow",
  },
  {
    id: "retrieval",
    title: "문서 검색과 RAG",
    description: "내 문서에서 근거를 찾아 답하는 AI를 이해하세요.",
    outcome: "LlamaIndex, Chroma, Qdrant로 검색 설계",
    icon: "search",
  },
  {
    id: "automation",
    title: "화면으로 만드는 업무 자동화",
    description: "작업 블록을 연결해 AI 업무 흐름을 만드세요.",
    outcome: "n8n과 Dify의 입력, 분기, 출력 이해",
    icon: "workflow",
  },
  {
    id: "local",
    title: "내 컴퓨터에서 AI 실행하기",
    description: "설치부터 첫 응답까지, 로컬 AI의 작동 원리를 익히세요.",
    outcome: "실행 환경 준비와 연결 문제 해결",
    icon: "monitor",
  },
  {
    id: "models",
    title: "모델 선택과 연결",
    description: "목적에 맞는 모델을 고르고 여러 제공자를 연결하세요.",
    outcome: "Hugging Face, Transformers, LiteLLM 이해",
    icon: "monitor",
  },
  {
    id: "tools",
    title: "AI 판단과 분류",
    description: "문장을 쓰는 AI와 판단을 돕는 AI를 구분해 보세요.",
    outcome: "Jev로 분류 기준과 검토 조건 정하기",
    icon: "sparkles",
  },
  {
    id: "evaluation",
    title: "AI 결과 평가와 실행 기록",
    description: "어디서 실패했는지 찾고 변경 전후의 품질을 비교하세요.",
    outcome: "LangSmith, Langfuse, promptfoo 활용 원리",
    icon: "search",
  },
  {
    id: "coding",
    title: "AI와 함께 코딩하기",
    description: "코드 도구에 작업을 맡기고 변경 결과를 확인하세요.",
    outcome: "Cursor, Claude Code, Aider, Continue 이해",
    icon: "monitor",
  },
  {
    id: "serving",
    title: "모델 배포와 운영",
    description: "여러 사용자의 요청을 처리하는 AI 서버를 이해하세요.",
    outcome: "vLLM, Ray Serve와 추론 운영",
    icon: "monitor",
  },
  {
    id: "tuning",
    title: "모델 학습과 데이터 관리",
    description: "미세 조정이 필요한 상황과 검증 방법을 익히세요.",
    outcome: "LoRA, PEFT, TRL과 실험 기록",
    icon: "workflow",
  },
  {
    id: "multimodal",
    title: "이미지와 음성 AI",
    description: "텍스트 외의 입력과 출력이 이어지는 과정을 살펴보세요.",
    outcome: "ComfyUI, Diffusers, Whisper, LiveKit 이해",
    icon: "sparkles",
  },
  {
    id: "reliability",
    title: "출력 검증과 안전한 실행",
    description: "AI가 만든 값과 실행할 수 있는 행동을 검사하세요.",
    outcome: "Pydantic AI와 NeMo Guardrails 이해",
    icon: "search",
  },
  {
    id: "apps",
    title: "AI 데모 앱 만들기",
    description: "모델을 다른 사람이 써볼 수 있는 화면으로 연결하세요.",
    outcome: "Gradio와 Streamlit의 역할 이해",
    icon: "monitor",
  },
] as const;
export type AiTrackId = (typeof AI_TRACKS)[number]["id"];
const LESSONS = [
  {
    id: "prompt-context",
    track: "fundamentals",
    title: "AI에게 필요한 맥락 전달하기",
    summary: "토큰과 컨텍스트를 이해하고, 질문에 필요한 정보와 성공 기준을 정합니다.",
    minutes: 6,
    level: "입문",
  },
  {
    id: "agent-workflow",
    track: "agents",
    title: "AI에게 일을 맡기는 순서",
    summary: "문의 접수부터 답변 검토까지, 한 번에 맡기던 일을 작은 단계로 나눕니다.",
    minutes: 7,
    level: "입문",
  },
  {
    id: "agent-tools",
    track: "agents",
    title: "AI가 도구를 쓸 때 필요한 약속",
    summary: "MCP와 도구 호출을 알아보고, 조회와 실행에 필요한 권한을 구분합니다.",
    minutes: 8,
    level: "기초",
  },
  {
    id: "crewai",
    track: "agents",
    title: "CrewAI로 여러 AI의 역할 나누기",
    summary: "조사와 검토를 나눌 때 필요한 역할, 전달할 결과, 종료 조건을 정합니다.",
    minutes: 8,
    level: "기초",
  },
  {
    id: "agent-protocols",
    track: "agents",
    title: "MCP와 A2A는 무엇을 연결할까요?",
    summary: "도구 연결과 에이전트 간 작업 위임의 차이를 구분합니다.",
    minutes: 7,
    level: "기초",
  },
  {
    id: "langchain",
    track: "frameworks",
    title: "LangChain으로 모델과 도구 연결하기",
    summary: "모델, 도구, 작업 지시가 어떻게 하나의 에이전트를 이루는지 살펴봅니다.",
    minutes: 8,
    level: "입문",
  },
  {
    id: "langgraph",
    track: "frameworks",
    title: "LangGraph로 멈추고 이어가는 흐름 만들기",
    summary: "노드, 상태, 분기를 이해하고 승인 대기 후 작업을 재개하는 순서를 배웁니다.",
    minutes: 9,
    level: "기초",
  },
  {
    id: "llamaindex",
    track: "retrieval",
    title: "LlamaIndex로 내 문서에서 답 찾기",
    summary: "문서를 나누고 검색해 근거와 함께 답하는 RAG의 흐름을 익힙니다.",
    minutes: 8,
    level: "입문",
  },
  {
    id: "vector-search",
    track: "retrieval",
    title: "Chroma와 Qdrant의 검색 원리",
    summary: "임베딩과 벡터 저장소를 알아보고, 유사도와 문서 접근 권한을 구분합니다.",
    minutes: 8,
    level: "기초",
  },
  {
    id: "haystack",
    track: "retrieval",
    title: "Haystack으로 검색 단계를 조합하기",
    summary: "키워드 검색, 벡터 검색, 재정렬을 연결하고 근거 누락을 확인합니다.",
    minutes: 8,
    level: "응용",
  },
  {
    id: "n8n",
    track: "automation",
    title: "n8n으로 반복 업무 연결하기",
    summary: "트리거부터 AI 분류와 저장까지 연결하고 중복 실행에 대비합니다.",
    minutes: 7,
    level: "입문",
  },
  {
    id: "dify",
    track: "automation",
    title: "Dify로 문서 안내 챗봇 설계하기",
    summary: "Workflow와 Chatflow를 구분하고 검색 결과가 없을 때의 답변을 정합니다.",
    minutes: 7,
    level: "입문",
  },
  {
    id: "local-start",
    track: "local",
    title: "로컬 AI, 설치 전에 알아둘 것",
    summary: "Ollama와 LM Studio로 모델을 준비하고 첫 질문을 보내는 방법을 배웁니다.",
    minutes: 8,
    level: "입문",
  },
  {
    id: "local-connect",
    track: "local",
    title: "로컬 AI가 응답하지 않을 때",
    summary: "실행 상태, 모델 이름, 연결 주소를 차례로 확인해 원인을 좁힙니다.",
    minutes: 7,
    level: "기초",
  },
  {
    id: "local-ui",
    track: "local",
    title: "llama.cpp와 Open WebUI의 역할",
    summary: "모델 실행 엔진과 채팅 화면을 구분하고 실제 연결 대상을 확인합니다.",
    minutes: 7,
    level: "기초",
  },
  {
    id: "huggingface",
    track: "models",
    title: "Hugging Face에서 모델 고르기",
    summary: "모델 카드와 Transformers의 역할을 이해하고 사용 조건을 확인합니다.",
    minutes: 7,
    level: "입문",
  },
  {
    id: "litellm",
    track: "models",
    title: "LiteLLM으로 여러 모델 연결하기",
    summary: "공통 호출 방식과 대체 모델을 알아보고, 전환 전 확인할 조건을 정합니다.",
    minutes: 8,
    level: "기초",
  },
  {
    id: "jev-decisions",
    track: "tools",
    title: "Jev는 어떤 일을 잘 맡을까요?",
    summary: "문의 분류 예제로 선택, 점수, 참과 거짓을 묻는 방법을 익힙니다.",
    minutes: 6,
    level: "입문",
  },
  {
    id: "jev-routing",
    track: "tools",
    title: "AI의 판단을 다음 작업에 연결하기",
    summary: "확신이 낮은 판단과 중요한 요청을 사람이 검토하도록 흐름을 만듭니다.",
    minutes: 8,
    level: "기초",
  },
  {
    id: "observability",
    track: "evaluation",
    title: "LangSmith와 Langfuse로 실패 원인 찾기",
    summary: "한 요청의 검색, 모델 호출, 응답 기록을 따라가며 문제 지점을 찾습니다.",
    minutes: 7,
    level: "입문",
  },
  {
    id: "promptfoo",
    track: "evaluation",
    title: "promptfoo로 변경 전후 비교하기",
    summary: "같은 사례와 기준으로 프롬프트와 모델 변경이 답변에 미치는 영향을 확인합니다.",
    minutes: 8,
    level: "기초",
  },
  {
    id: "rag-eval",
    track: "evaluation",
    title: "Ragas로 검색과 답변을 따로 평가하기",
    summary: "정답 문서를 못 찾은 경우와 근거를 벗어난 답변을 구분합니다.",
    minutes: 8,
    level: "응용",
  },
  {
    id: "coding-assistants",
    track: "coding",
    title: "코딩 에이전트에 작은 변경 맡기기",
    summary: "Cursor, Claude Code, Aider, Continue의 공통 작업 흐름을 익힙니다.",
    minutes: 8,
    level: "입문",
  },
  {
    id: "inference-serving",
    track: "serving",
    title: "vLLM으로 이해하는 모델 서빙",
    summary: "모델 로딩, 요청 대기, 토큰 생성을 구분하고 메모리 부족에 대응합니다.",
    minutes: 9,
    level: "응용",
  },
  {
    id: "serving-scale",
    track: "serving",
    title: "Ray Serve로 요청을 나눠 처리하기",
    summary: "복제본, 대기열, 자동 확장과 지연 시간의 관계를 배웁니다.",
    minutes: 9,
    level: "응용",
  },
  {
    id: "lora-training",
    track: "tuning",
    title: "LoRA와 PEFT로 미세 조정 이해하기",
    summary: "PEFT, TRL, Unsloth의 역할과 검색 보강으로 해결할 문제를 구분합니다.",
    minutes: 9,
    level: "응용",
  },
  {
    id: "training-data",
    track: "tuning",
    title: "DVC와 MLflow로 실험 비교하기",
    summary: "데이터 버전과 학습 설정을 남기고 평가 데이터가 섞이지 않게 관리합니다.",
    minutes: 8,
    level: "기초",
  },
  {
    id: "image-workflow",
    track: "multimodal",
    title: "ComfyUI와 Diffusers로 이미지 흐름 이해하기",
    summary: "모델, 프롬프트, 시드와 생성 설정을 구분해 결과를 비교합니다.",
    minutes: 8,
    level: "기초",
  },
  {
    id: "voice-workflow",
    track: "multimodal",
    title: "Whisper와 LiveKit으로 음성 흐름 이해하기",
    summary: "음성 인식, 답변 생성, 음성 출력을 나누고 끼어들기를 처리합니다.",
    minutes: 8,
    level: "기초",
  },
  {
    id: "output-validation",
    track: "reliability",
    title: "Pydantic AI로 답변 형식 검증하기",
    summary: "스키마 검사와 업무 규칙을 구분하고 잘못된 출력을 처리합니다.",
    minutes: 8,
    level: "기초",
  },
  {
    id: "guardrails",
    track: "reliability",
    title: "NeMo Guardrails로 실행 범위 정하기",
    summary: "입출력 검사와 도구 권한을 나누고 방어가 필요한 지점을 찾습니다.",
    minutes: 8,
    level: "응용",
  },
  {
    id: "ai-demo",
    track: "apps",
    title: "Gradio와 Streamlit으로 첫 화면 설계하기",
    summary: "입력, 실행 중, 결과, 오류를 구분하는 AI 데모 화면을 구성합니다.",
    minutes: 7,
    level: "입문",
  },
] as const;
export type AiLessonId = (typeof LESSONS)[number]["id"];
const LESSON_TOOLS: Record<AiLessonId, string[]> = {
  "prompt-context": ["프롬프트", "컨텍스트", "토큰"],
  "agent-workflow": ["에이전트", "워크플로우", "도구 호출"],
  "agent-tools": ["MCP", "도구 호출"],
  crewai: ["CrewAI", "멀티 에이전트"],
  "agent-protocols": ["MCP", "A2A"],
  langchain: ["LangChain", "랭체인"],
  langgraph: ["LangGraph", "랭그래프", "체크포인트"],
  llamaindex: ["LlamaIndex", "라마인덱스", "RAG"],
  "vector-search": ["Chroma", "Qdrant", "pgvector", "Sentence Transformers", "임베딩"],
  haystack: ["Haystack", "하이브리드 검색", "리랭킹"],
  n8n: ["n8n", "웹훅"],
  dify: ["Dify", "Chatflow"],
  "local-start": ["Ollama", "올라마", "LM Studio", "로컬 LLM"],
  "local-connect": ["Ollama", "localhost"],
  "local-ui": ["llama.cpp", "GGUF", "Open WebUI"],
  huggingface: ["Hugging Face", "Transformers", "허깅페이스"],
  litellm: ["LiteLLM", "모델 게이트웨이"],
  "jev-decisions": ["Jev", "TypeSafe", "구조화된 판단"],
  "jev-routing": ["Jev", "확신도"],
  observability: ["LangSmith", "Langfuse", "트레이싱"],
  promptfoo: ["promptfoo", "회귀 평가"],
  "rag-eval": ["Ragas", "RAG 평가"],
  "coding-assistants": ["Cursor", "Claude Code", "Aider", "Continue"],
  "inference-serving": ["vLLM", "배치 처리", "KV 캐시"],
  "serving-scale": ["Ray Serve", "자동 확장"],
  "lora-training": ["LoRA", "QLoRA", "PEFT", "TRL", "Unsloth"],
  "training-data": ["DVC", "MLflow"],
  "image-workflow": ["ComfyUI", "Diffusers", "확산 모델"],
  "voice-workflow": ["Whisper", "LiveKit", "STT", "TTS"],
  "output-validation": ["Pydantic", "Pydantic AI", "JSON Schema"],
  guardrails: ["NeMo Guardrails", "프롬프트 인젝션"],
  "ai-demo": ["Gradio", "Streamlit"],
};
export const AI_LESSONS = LESSONS.map((lesson) => ({ ...lesson, tools: LESSON_TOOLS[lesson.id] }));
export const aiLessonById = (id: string) => AI_LESSONS.find((lesson) => lesson.id === id);
export const AI_CONTENT_REVIEWED = "2026-09-21";
